# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    - name: Build
      run: go build -o gofiles-amd64 -v ./...
    - name: Test
      run: go test -o gofiles-amd64 -v ./...
    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: gofiles-amd64
        path: gofiles-amd64

  build-macos:
      runs-on: macos-12
      steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Build
        run: go build -o gofiles-macos
      - name: Test
        run: go test -o gofiles-macos
  
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: gofiles-macos
          path: gofiles-macos

  release:
    runs-on: ubuntu-latest
    needs: [build-linux, build-macos]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Download artifact
      uses: actions/download-artifact@v2
      # with:
      #   name: gofiles-amd64
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          gofiles-amd64
          gofiles-macos
        tag_name: ${{ github.ref_name }}
        title: Release ${{ github.ref_name }}

    - name: Publish Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          gofiles-amd64
          gofiles-macos
        tag_name: ${{ github.ref_name }}
        title: Release ${{ github.ref_name }}
        overwrite: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # - uses: wangyoucao577/go-release-action@v1
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     goos: linux
    #     goarch: amd64
